// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace openfda.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250213171436_UpdatedSchemas")]
    partial class UpdatedSchemas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AdverseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DrugId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DrugId");

                    b.ToTable("AdverseEvents");
                });

            modelBuilder.Entity("Drug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActiveIngredient")
                        .HasColumnType("longtext");

                    b.Property<string>("DosageAndAdministration")
                        .HasColumnType("longtext");

                    b.Property<string>("InactiveIngredient")
                        .HasColumnType("longtext");

                    b.Property<string>("IndicationsAndUsage")
                        .HasColumnType("longtext");

                    b.Property<Guid>("OpenFdaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PackageLabelPrincipalDisplayPanel")
                        .HasColumnType("longtext");

                    b.Property<string>("Purpose")
                        .HasColumnType("longtext");

                    b.Property<string>("SplProductDataElements")
                        .HasColumnType("longtext");

                    b.Property<string>("Warnings")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OpenFdaId");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("OpenFda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GenericName")
                        .HasColumnType("longtext");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OpenFda");
                });

            modelBuilder.Entity("AdverseEvent", b =>
                {
                    b.HasOne("Drug", "Drug")
                        .WithMany("AdverseEvents")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("Drug", b =>
                {
                    b.HasOne("OpenFda", "OpenFda")
                        .WithMany("Drugs")
                        .HasForeignKey("OpenFdaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpenFda");
                });

            modelBuilder.Entity("Drug", b =>
                {
                    b.Navigation("AdverseEvents");
                });

            modelBuilder.Entity("OpenFda", b =>
                {
                    b.Navigation("Drugs");
                });
#pragma warning restore 612, 618
        }
    }
}
